-
  name: Apply for this opportunity
  editable: True
  description:
    default: |
      The buyer will compare your response with other seller responses to create a shortlist for the evaluation stage. To progress, consider each answer carefully.

      As a guide, you could explain:

      - what the situation was
      - the work the specialist or team completed
      - what the results were

      You can reuse examples if you wish.

  questions:
    - essentialRequirements
    - niceToHaveRequirements
    - availabilityOutcomes
    - availabilitySpecialists
    - dayRate
    - attachedDocumentURL
    - respondToEmailAddress
